### PR TITLE
Use Case Diagr

### PR DESCRIPTION
**Pull request by momodonatien**

### CODE REVIEW

**Comment by azerupi** [comment]
Is there a reason to have the "commissionner" ? Considering the client has no additional properties, wouldn't it be enough to just have the client and the storekeeper inheriting from him directly?

Other small nit, storekeeper is called "Employee" in other diagrams I think, it would be good to choose one term and stick with it. :)

**Comment by momodonatien** [comment]
Concerning the commissioner, it's true he doesn't really needs to be there
but I don't see why he SHOULDN'T be. But if everyone agrees he shouldn't
then no worries I will remove him.
Concerning the translation for "magasinier" it should be "storekeeper" and
not "employee" because an employee can be anyone employed by the company
but a storekeeper , "keeps and handles the store" .....
William used storekeeper too which is the right word to use.

**Comment by azerupi** [comment]
@bluebeel @WilliamHdd @JonathanPetit thoughts about the *commissioner*?

> Concerning the translation for "magasinier" it should be "storekeeper" and
not "employee" because an employee can be anyone employed by the company

Yes, makes sense. Let's stick with *storekeeper* then :)

**Comment by JonathanPetit** [comment]
About the _commisioner_, i think it is not necessary. I don't see why he is different from client or _storekeeper_. @momodonatien What caracteristics more than client or storekeeper has he ?

**Pull request merged**
