### PR TITLE
Activity Diagram

### PR DESCRIPTION
**Pull request by WilliamHdd**
Could you guys give a feedback about this version ? What do you think needs to be changed ?

### CODE REVIEW

**Comment by azerupi** [comment]
Drop an image of the diagram here (or in the tracking issue #4) , it will be easier for us than checking out your branch :wink:

**Comment by WilliamHdd** [comment]
activitydiagram1

**Comment by WilliamHdd** [comment]
activitydiagram1

**Comment by WilliamHdd** [comment]
activitydiagram1

**Comment by WilliamHdd** [comment]
activitydiagram1

**Comment by WilliamHdd** [comment]
activitydiagram1

**Pull request closed without merging**
